platform :ios, '11.0'

target 'Segment-Firebase_Example' do
  # Use default subspec
  pod 'MetarouterAnalytics-Firebase', :path => '../'
  
  target 'Segment-Firebase_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
